truenas/catalog_validation

catalog_validation/git_utils.py
This commit adds changes to not run CI on a library train as the charts under library train are not meant to be deployed directly and are in fact helm library charts.
Closes truenas/charts#25
=> Donot run CI on library train

catalog_validation/validation.py, debian/rules
This PR introduces following changes:
1) Allow validating item versions to be configurable
2) Do not install helm while packaging catalog_validation, the idea initially was to use this debian package in CI but later the approach taken was different and this is no longer required.
=> Allow validating item versions to be configurable

catalog_validation/scripts/charts_validate.py
This adds a uninstall of a chart after testing it.
It might seem like a crude solution to #12
But removing every chart, also ensures there are 
not issues when uninstalling charts, which is actually something we would want to verify anyway.
Fixes #12
=> Uninstall release after testing

catalog_validation/validation.py
This commit adds changes to not traceback when we are dealing with invalid catalogs which might have files instead of directories for catalog items
=> Do not traceback for invalid catalog(s)

catalog_validation/scripts/charts_validate.py
Large images like collabora can take some time to download which results in the existing command timing out. This commit increases the timeout value to avoid such cases.
=> Increase timeout for installing k8s resources

catalog_validation/schema/attrs.py
- Catalog validation for **enum**  schema does not fail when unexpected key,values are added.
- Catalog validation does not fail when we add **subquestions** without adding **show_subquestions_if**.
- Added **additionalProperties: False** in **enum** schema under **items**  key and removed sqaure brackets **[ ]** form **items**.
- Added **dependencies** key in catalog validation schema.
=> Catalog validation failing due to minor schema issues

catalog_validation/items/catalog.py, catalog_validation/items/features.py, catalog_validation/items/items_util.py, catalog_validation/items/questions_utils.py, catalog_validation/items/validate_utils.py
This PR introduces changes to move logic from middleware to catalog_validation so that we can have a github action update catalog information on each master push to truenas/charts and the same code can be reused in middleware by importing the library.
=> Move logic from middleware to catalog_validation to retrieve catalog details

catalog_validation/items/utils.py
This PR adds json schema for catalog details which will be used in middleware for validating that the `catalog.json` specified file in catalogs actually conforms to the format we want.
=> Specify json schema for catalog details

.github/workflows/test.yaml, catalog_validation/pytest/requirements.txt, catalog_validation/pytest/unit/test_catalog_validate.py, catalog_validation/pytest/unit/test_items_util.py, catalog_validation/pytest/unit/test_normalise_questions.py, catalog_validation/pytest/unit/test_schema.py, requirements.txt
Unit tests have been added for following scenarios:
1. Catalog validation logic
2. Parsing item details
3. Normalizing questions in an item's questions.yaml
=> Add unit tests for catalog validation logic

catalog_validation/items/items_util.py, catalog_validation/items/utils.py, catalog_validation/pytest/unit/test_items_util.py, requirements.txt
UI team has requested to have a `last_update` field for newer Apps UI. This posed a problem wrt performance and the solution to that has been to add this field to the cached metadata file for each catalog which is generated on the catalog side, hence middleware is spared the overhead which would not have been possible to manage otherwise.
It will show up in the following format currently:
```
"last_update": "2023-02-01 22:55:31",
```
=> Add last update field for apps and app versions

catalog_validation/git_utils.py, catalog_validation/items/catalog.py, catalog_validation/items/utils.py, catalog_validation/validation.py
This PR adds changes to not consider `ix-dev` directory as a train. Motivation behind the change is that under this directory we can have direct app directories without versions, this will help us retain git history for an app in question and we can copy paste the helm chart details to the stable train from here.
=> NAS-120548 / 23.10 / Don't consider "ix-dev" directory as a train

catalog_validation/items/items_util.py
Helm has deprecated specifying metadata in charts top level dict and custom metadata i.e `title` can be specified under `annotations` now which is what we should be doing moving forward.
=> NAS-121129 / 23.10 / Retrieve catalog item title from annotations

catalog_validation/schema/attrs.py
If app developer uses `valid_chars` attribute to validate a value specified by user, the error is vague i.e does not match pattern.
It does not help tell the user that he needs to follow this specific order to be able to correctly specify the value in question so now the dev can specify a custom error message which will better guide the user on what to input for a field which is being validated by `valid_chars`.
=> NAS-120646 / 23.10 / Allow app developer to add custom error message

catalog_validation/items/questions_utils.py, catalog_validation/items/utils.py, catalog_validation/schema/features.py
`filesystem.add_to_acl` has been added to allow app devs to correctly specify ACLs for host paths. A feature `normalize/acl` has been added which app devs can specify to consume the new feature.
=> NAS-120252 / 23.10 / Allow specifying ACLs for apps

catalog_validation/schema/attrs.py
We were not validating the type of content specified under `$ref` which resulted to unintended behaviour as the expectation is that it should be a string.
Properly validate that each entry under a `$ref` should be a string.
=> NAS-121419 / 23.10 / Properly validate $ref value

catalog_validation/schema/attrs.py
We were not validating the type of content specified under `$ref` which resulted to unintended behaviour as the expectation is that it should be a string.
Properly validate that each entry under a `$ref` should be a string.
Original PR: https://github.com/truenas/catalog_validation/pull/54
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121419
=> NAS-121419 / 22.12.3 / Properly validate $ref value (by Qubad786)

catalog_validation/pytest/unit/test_items_util.py
After installing all packages in book worm this test was still failing because of the following reasons
1. `os.path.isdir` is mocked to true in all cases
2. `os.listdir` is mocked to the following list `['upgrade_info.json', '1.3.37', 'upgrade_strategy', 'item.yaml']` when `get_item_details_impl` func is run and it consider upgrade_info, upgrade_strategy, item.yaml as a folder and tries to parse its version which gives values error from that package. That ultimately leads to test failure
following is the code that emit the error.
=> NAS-121725 / 23.10 / Fix failed test in test-utils

catalog_validation/schema/attrs.py, catalog_validation/schema/migration_schema.py, requirements.txt
Json schema validation was failing when we updated to bookworm with the problem being invalid newer json schema being specified for validation.
For `array` type objects when `items` is specified as a list it is expected that each item in the value which is to be validated will be mapped with each entry specified in `items` list. If the values are more in either list validation fails..in our case we want all the items to be of type `string` and in that case `items` should not be a list but rather the type we want all of the items to be enforced in the actual value of list (ref: https://json-schema.org/understanding-json-schema/reference/array.html)
=> NAS-121724 / 23.10 / Fix json schema list attrs usages

catalog_validation/items/items_util.py, catalog_validation/utils.py, catalog_validation/validation.py
For most cases we would want app developers to be limited to what they try to consume from the host but in some cases it is necessary for the app to function.
A good example is `netdata` application, in order for it to gather statistics it needs access to sysfs which is fine but an end user should be aware of what the app in question is trying to consume. Changes have been made which expose the following information for now and we can extend this as required:
```
runAsContext:
- userName: root
groupName: root
gid: 0
uid: 0
description: "Why this needs to be done"
capabilities:
- name: SYS_PTRACE
description: "This is being used to do X thing"
hostMounts:
- hostPath: "/proc"
description: "Required by netdata for xyz"
```
=> Add ability to specify application metadata

catalog_validation/items/items_util.py, catalog_validation/items/utils.py, catalog_validation/pytest/unit/test_items_util.py
It was requested by the UI team to have the `home` attribute be made available in the `app.available` response.
=> NAS-121808 / 23.10 / Add home attribute to app details

catalog_validation/items/items_util.py, catalog_validation/pytest/unit/test_items_util.py, catalog_validation/validation.py, catalog_validation/validation_utils.py
Helm does not like having a list of strings under a string key in `annotations` in `Chart.yaml`.
It seems best that we have screenshots defined in `item.yaml` instead of `Chart.yaml` as that is not taken into account by helm.
=> NAS-121986 / 23.10 / Specify screenshots in item.yaml

catalog_validation/schema/migration_schema.py, catalog_validation/validation.py
The catalog_validate app does not support validation of app migrations. It is crucial for these migration files to be executable, as failing to execute them can result in migrations being missed without the developer being notified in a timely manner.
To address this problem,  add validation for app migration files and ensuring that these files are executable. By performing this validation, app developers can be alerted if any migration files are not executable, enabling them to take necessary actions to ensure the execution of these migrations.
=> NAS-122209 / 23.10 / Add app migration file executable validation

catalog_validation/schema/attrs.py, catalog_validation/schema/schema_gen.py
Expose `hostpathdirectory` and `hostpathfile` schemas to app developers so that they can consume it to validate if the host path being specified is a directory/file and have more validation in place to properly validate their app's values to conform to what's actually required by the app.
=> NAS-122715 / 23.10 / Allow validating path is dir/file on host in apps

catalog_validation/items/items_util.py, catalog_validation/items/questions_utils.py
A `ref` is being added so questions in an app which consume ports and allow it to be user configurable have a way to show unused ports which can actually be used by the app.
=> NAS-122338 / 23.10 / Add unused ports to questions if specified by question

catalog_validation/git_utils.py, catalog_validation/validation.py
CI was failing with bump version error even when the only file changed was **upgrade_strategy**
The condition is added so that if only **upgrade_strategy** or **upgrade_info** file is changed CI will not fail with the above mentioned error.
=> NAS-124275 / 24.04 / Skip version bump validation for upgrade strategy files

catalog_validation/ci/utils.py, catalog_validation/ci/validate.py, catalog_validation/scripts/catalog_update.py
In the current Continuous Integration (CI) process, all versions of apps are being removed except for the last/latest version. However, in certain cases, it is necessary to keep previous app versions, such as for upgrading between major versions (e.g., Nextcloud, which doesn't allow direct multiple major version jumps).
To address this issue, a new feature has been introduced in the app CI pipeline. App developers are required to specify a list of versions that they wish to preserve in a `to_keep_versions.yaml` file, which should be placed within the `ix-dev` apps folder. The CI process will then refrain from deleting the versions that have been defined in this file.
For example:
```yaml
- 1.0.3
- 1.0.33
```
This change allows developers to retain specific app versions as needed for …
=> NAS-124094 / 24.04 / Add to keep version file to preserve some app versions

catalog_validation/ci/utils.py, catalog_validation/git_utils.py
The issue arises from `catalog_update` publishing apps that have only been updated in the `to_keep_versions.yaml` file without bumping their versions. These apps already exist in the catalog because the versions specified in this file are not being deleted by `catalog_update`, resulting in this problem. The problem is exacerbated when validating version bumps for apps with multiple versions. It can mistakenly pick a lower version of an app that hasn't been deleted and compare it to the current version. Changes in the `to_keep_versions.yaml` file trigger `catalog_update`, even though version bumps have not occurred.
To address this issue, the solution involves sorting the versions list to ensure the latest version is considered during version bump validation. Additionally, changes are …
=> NAS-124604 / 24.04 / Make sure versions are properly reflected

catalog_validation/ci/utils.py, catalog_validation/ci/validate.py
During the upgrade process, certain upgrade strategies in the `charts` repository are found to be non-executable. This issue results in the failure of app upgrades.
To address this problem, validations have been added to prevent the execution of non-executable upgrade strategies.
The added validations ensure that only executable upgrade strategies are used during the app upgrade process, thereby preventing failures and ensuring a smooth upgrade experience.
=> NAS-124625 / 24.04 / Add update strategy validation

catalog_validation/items/utils.py
This commit adds changes to add a description for user/group id so user knows that he should apply ACLs keeping in line with the run as user context of the app because if misconfigured ACLs were applied the app might not work properly.
=> NAS-125107 / 24.04 / Add a description for the user/group id

catalog_validation/items/utils.py
Applying ACL for a non-empty path required `force flag` to be `true` which was `false` by default and not user configurable.
This PR adds the option for the user to configure `force flag` as desired during chart create or update process.
=> NAS-125106 / 24.04 / Add user-selectable force option in ACL entries

catalog_validation/items/utils.py
It was requested by Stavros that we backport ACL changes so users can make use of the new force flag properly.
Following changes have been backported:
1. Change type from `string` to `hostpath`
2. Change label
3. Add help text for ID
4. Add `force flag` option for user to add ACL for non-empty paths
=> NAS-125528 / 23.10.2 / Backport ACL flag changes

catalog_validation/items/utils.py
It was requested by Stavros that we backport ACL changes so users can make use of the new force flag properly.
Following changes have been backported:
1. Change type from `string` to `hostpath`
2. Change label
3. Add help text for ID
4. Add `force flag` option for user to add ACL for non-empty paths
Original PR: https://github.com/truenas/catalog_validation/pull/85
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125528
=> NAS-125528 / 23.10.1 / Backport ACL flag changes (by Qubad786)

catalog_validation/items/items_util.py
This commit adds changes so that consumer can toggle a flag to add/remove keys related to items when we are actually retrieving it's complete details.
=> NAS-126049 / 24.04 / Optionally add attributes to item details base

catalog_validation/schema/attrs.py, catalog_validation/schema/schema_gen.py
PR adds new Text Class which can take string / text data of upto 1 MiB. Motivation is to allow UI to make a distinction that this is not a regular string field and UI can adjust size of the field accordingly then in the UI.
After discussing with Stavros - this field will be useful to specify data for configmaps which we might want to go as is like configurations etc.
(Jira issue: https://ixsystems.atlassian.net/browse/TNCHARTS-443 not sure how the bug clerk integration works for tncharts issues)
=> Add a text field schema for UI

catalog_validation/schema/attrs.py
UI needed a language type for text field in order to load language specific syntax highlighter
PR adds the validation to check that language type specified by app developer is either YAML, JSON, TOML, or plain text. Schema for text type variable can be something like: 
```
"variable": "testtext",
"label": "Test Text Field",
"group": "Plex Configuration",
"description": "This is to test text schema",
"schema": {
"type": "text",
"language": "yaml",
"default": ""
}
=> NAS-127699 / 24.04 / Add validation for language type of text field schema
